# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewsync" do
  name "brewsync"
  desc "Declarative, Git-backed Homebrew management for multi-machine setups."
  homepage "https://github.com/jtbrough/brewsync"
  version "0.9.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewsync"

  on_macos do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_x86_64.tar.gz"
      sha256 "61cdb0ca615f1604d8c9c07358b4e5d5d14d15fd2894b851866df506813998bf"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_arm64.tar.gz"
      sha256 "b01ba4863b73d89ca630e31bd8cee8267c5ccae6ac67acb92e1c4892e5546c54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_x86_64.tar.gz"
      sha256 "f6a7ae6b531cc89cb81a31970066d101ea0ea080fd8ab56df25c21b7b013136f"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_arm64.tar.gz"
      sha256 "6f131eb4e4653a377586fb25858bc2dc18ffc780b2cc53d5d95d942900fd3ee6"
    end
  end

  # No zap stanza required
end
