# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewsync" do
  name "brewsync"
  desc "Declarative, Git-backed Homebrew management for multi-machine setups."
  homepage "https://github.com/jtbrough/brewsync"
  version "0.9.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewsync"

  on_macos do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_x86_64.tar.gz"
      sha256 "7ad420e1f6e04522545d637b436106fa375520a184f41044b4a77555e028450f"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_arm64.tar.gz"
      sha256 "e69379a96841b02c2931436064f2d734295f02882fa559d7e390a6ba8959276d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_x86_64.tar.gz"
      sha256 "c7a8f7e4ed87969ac851ddcf12f547d1e7a366a994ecde4a43b37258bf4f30fe"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_arm64.tar.gz"
      sha256 "feb7461fc18dd20c7440f346ab3c7a1a134c1f709ce9022620fe20d5f1f8a389"
    end
  end

  # No zap stanza required
end
