# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewsync" do
  name "brewsync"
  desc "Declarative, Git-backed Homebrew management for multi-machine setups."
  homepage "https://github.com/jtbrough/brewsync"
  version "0.9.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewsync"

  on_macos do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_x86_64.tar.gz"
      sha256 "493a7937e2c2b34b091d56d4edc571feec9eca480c55e43419c71d54c5e6565f"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Darwin_arm64.tar.gz"
      sha256 "2b86e353fa541438edb990b1d7d7c04f2b30b98568e4dcc70252525101e7b114"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_x86_64.tar.gz"
      sha256 "0a4c27dfa44600e6ab583d7b61618efd9b5cabc2969e4119ce404cf3565c1763"
    end
    on_arm do
      url "https://github.com/jtbrough/brewsync/releases/download/v#{version}/brewsync_Linux_arm64.tar.gz"
      sha256 "abff3b6c2457a8ee7e216ff964d9d13270f70f5af72cd279002bc47818c211df"
    end
  end

  # No zap stanza required
end
