# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewsync < Formula
  desc "Declarative, Git-backed Homebrew management for multi-machine setups."
  homepage "https://github.com/jtbrough/brewsync"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtbrough/brewsync/releases/download/v1.0.1/brewsync_Darwin_x86_64.tar.gz"
      sha256 "dc3dac6b3aa32ba29573c2515dca4944624af35417c7beb3593ec5536e814d0e"

      def install
        bin.install "brewsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtbrough/brewsync/releases/download/v1.0.1/brewsync_Darwin_arm64.tar.gz"
      sha256 "f73f628690951d076c941d4971dccde8c071f269538f09ac64cd21466e2a90a5"

      def install
        bin.install "brewsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtbrough/brewsync/releases/download/v1.0.1/brewsync_Linux_x86_64.tar.gz"
      sha256 "623622724cadeb47e14c6fc82239ba2ceb1947f9ac5968b5edafb3ea06b99d53"
      def install
        bin.install "brewsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtbrough/brewsync/releases/download/v1.0.1/brewsync_Linux_arm64.tar.gz"
      sha256 "c48667bb1e2276cb37edbb1715506f7b35ec3a47ab70c2da95fedba737e879e0"
      def install
        bin.install "brewsync"
      end
    end
  end

  test do
    system "#{bin}/brewsync version"
  end
end
