# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewsync < Formula
  desc "Declarative, Git-backed Homebrew management for multi-machine setups."
  homepage "https://github.com/jtbrough/brewsync"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtbrough/brewsync/releases/download/v0.9.0/brewsync_Darwin_x86_64.tar.gz"
      sha256 "bc2cec0b1cbeef407a770625afa540d5b51b7f937b8aa0286f44fd98686938c3"

      def install
        bin.install "brewsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtbrough/brewsync/releases/download/v0.9.0/brewsync_Darwin_arm64.tar.gz"
      sha256 "3ecf39a53f2ce78cf0dcbebc6ebcefa26366f4a379ba2431564dc9a133999419"

      def install
        bin.install "brewsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtbrough/brewsync/releases/download/v0.9.0/brewsync_Linux_x86_64.tar.gz"
      sha256 "58469e0423258009bad0bf2e9362df2eccde88a53e9ded3b998055b93575fb1d"
      def install
        bin.install "brewsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtbrough/brewsync/releases/download/v0.9.0/brewsync_Linux_arm64.tar.gz"
      sha256 "9efd35b74234d64a42d76f1cb0492589513ac15c8d9dcf3cd8a9161c4affff72"
      def install
        bin.install "brewsync"
      end
    end
  end

  test do
    system "#{bin}/brewsync version"
  end
end
